/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EpicGame } from "./EpicGame";
export * as factories from "./factories";
export { EpicGame__factory } from "./factories/EpicGame__factory";
